swagger: "2.0"
info:
  version: 0.0.1
  title: Express API Project
  description: Basic API project structure using node and express

consumes:
  - application/json
produces:
  - application/json

paths:
  /api/users:
    get:
      description: Hello world
      operationId: users
      responses:
        default:
          description: Return Hello world
          schema:
            type: object
            example:
              message: "Hello world"